name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMmE0YWZiMGEtZjU0OC00NzM1LWFkYzEtYzEwYjdkYjJiNzNhIiwidGVuYW50X2lkIjoiYjUzZDY0ZGNlOWI3NjA1MmY3OTYxNzU4OTBiYmU3NDRjZjdhMWM1ODBjNGRlOWUxYmYwMDBhMjM3NTE0YTY2MCIsImludGVybmFsX3NlY3JldCI6ImUxNDc4NGUwLWQwMzMtNDEyMi1hYTZiLTJlZDFkMzViZTU5OSJ9.ZcH-qvrM1u1sFrKRQKIHC7uSaFyYspsGqS25jxQYSFI"
JWT_SECRET="123abc123"