name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNThkNDY1NDUtYWNmNC00ZTQ2LTg5ZjctYWFkZWMyMDU0MWI1IiwidGVuYW50X2lkIjoiYjUzZDY0ZGNlOWI3NjA1MmY3OTYxNzU4OTBiYmU3NDRjZjdhMWM1ODBjNGRlOWUxYmYwMDBhMjM3NTE0YTY2MCIsImludGVybmFsX3NlY3JldCI6ImUxNDc4NGUwLWQwMzMtNDEyMi1hYTZiLTJlZDFkMzViZTU5OSJ9.3ZQXW-j5Kxg04zZL8LRXoLLAuhRpmx3FIQtFDidULSU"
JWT_SECRET="123abc123"